version: '3.9'

services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:24.0.3
    ports:
      - "18080:8080"
      - "18443:8443"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev
    volumes:
      #      - keycloak_data:/opt/jboss/keycloak/standalone/data
      - keycloak_data:/opt/keycloak/data/h2
    networks:
      - iam_network

volumes:
  keycloak_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: C:/Users/lenovo/Docker/keycloak

networks:
  iam_network:
    driver: bridge
