spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:18080/realms/celestial-forge"
          jwk-set-uri: "http://localhost:18080/realms/celestial-forge/protocol/openid-connect/certs"

